### ISSUE TITLE
Update schema to reflect changes in gene document

### ISSUE THREAD

**Issue by mycrobe** [warelab/gramene-swagger#3]
The schema should be updated to reflect changes in the document format that are defined in the following issues:

warelab/gramene-mongodb#16
warelab/gramene-mongodb#17
warelab/gramene-mongodb#18
warelab/gramene-mongodb#19
warelab/gramene-mongodb#20
warelab/gramene-mongodb#21

**Comment by ajo2995** [comment]
fixed in commit cc9b230
