### ISSUE TITLE
export bed files of various gene structure features

### ISSUE THREAD

**Issue by ajo2995** [warelab/gramene-swagger#6]
Currently, you can export a bed file for the whole gene interval from the solr endpoint with columns chr, start, end, id, taxon_id, and strand. The same info can be extracted from the mongo docs with wt=tab and fl=location.region,location.start,location.end._id,taxon_id,location.strand but you'll have to make do without the fancy filters.

We need to be able to export specific features: gene, exon, intron, CDS, 5'UTR, and 3'UTR. When there are multiple transcripts in a gene model, you need to specify a method for combining the intervals: canonical, union, or intersection. Define query parameters bedFeature (defaults to gene) and bedCombiner (defaults to canonical) that are relevant when wt=bed.

The solr documents don't contain the necessary info to extract these features, but doing this with mongo documents means its a two step job to export interesting subsets of genes (use solr to build up an idList to pass to the mongo interface). Current mongo docs only contain the canonical transcript, so it is possible to implement the default bedCombiner now, and the other modes once we have all isoforms in the genes docs.

**Comment by ajo2995** [comment]
It was suggested that we set up another service that does this in order to streamline the gramene-swagger server. This service can use gramene-search-client, but additional result types might be required. All we need from solr is a list of ids, and from mongo we need either location or gene_structure depending on the bed feature

**Comment by ajo2995** [comment]
For now, we will write a module to do the bed file formatting from mongo genes docs. It should in theory run concurrently with other requests in node.js, but if there is a performance hit, we can move this to another service.

**Comment by mycrobe** [comment]
The good news is that unlike for SOLR, the mongo documents are received by the REST server as a stream of documents, so this should be simple to implement using, for example, `through2`:

Implement a new transformer in a separate module, then use it like we use the csvTransformer [in the mongo controller](https://github.com/warelab/gramene-swagger/blob/dev/api/controllers/mongo.js#L41):

(The transformer defined on that line is used [on line 51](https://github.com/warelab/gramene-swagger/blob/dev/api/controllers/mongo.js#L51) to transform the file: )
